<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="<?php echo csrf_token(); ?>">
  <title>Virtual MRT Card - MRT Ticketing System</title>

  {{-- Load Vite / built assets using Laravel's mix-like manifest if present in public/build --}}
  <?php if (file_exists(public_path('build/manifest.json'))):
    $manifest = json_decode(file_get_contents(public_path('build/manifest.json')), true);
    // try to find the main entry generated by Vite (commonly resources/js/app.tsx or main.tsx)
    $entry = null;
    foreach ($manifest as $key => $val) {
      if (strpos($key, 'resources/js') !== false || strpos($key, 'resources/js') !== false) {
        $entry = $val;
        break;
      }
    }
  endif; ?>

  <?php if (isset($entry) && isset($entry['css'])): ?>
    <?php foreach ($entry['css'] as $cssPath): ?>
      <link rel="stylesheet" href="/build/<?php echo $cssPath; ?>">
    <?php endforeach; ?>
  <?php endif; ?>

  <?php if (isset($entry) && isset($entry['file'])): ?>
    <script type="module" src="/build/<?php echo $entry['file']; ?>" defer></script>
  <?php else: ?>
    {{-- Fallback to the generic app bundle name used by this project --}}
    <script type="module" src="/build/assets/main.js" defer></script>
  <?php endif; ?>
</head>
<body>
  <div id="app"></div>
</body>
</html>
